import typing
from typing_extensions import ParamSpec


class SupportsRichComparison(typing.Protocol):
    def __lt__(self, other: typing.Any, /) -> bool: ...
    def __le__(self, other: typing.Any, /) -> bool: ...
    def __gt__(self, other: typing.Any, /) -> bool: ...
    def __ge__(self, other: typing.Any, /) -> bool: ...
    def __eq__(self, other: typing.Any, /) -> bool: ...
    def __ne__(self, other: typing.Any, /) -> bool: ...


class SupportsKeysAndGetItem(typing.Protocol):
    def __getitem__(self, name: typing.Any, /) -> typing.Any: ...

    def keys(self) -> typing.Iterable[typing.Any]: ...


class SupportsLen(typing.Protocol):
    def __len__(self) -> int: ...


_P = ParamSpec("_P")
_R = typing.TypeVar("_R")

Function = typing.Callable[_P, _R]
CoroutineFunction = typing.Callable[_P, typing.Awaitable[_R]]
